version: '3.8'

services:
  next-app:
    build: ./app/my-app
    ports:
      - '3000:3000'
    volumes:
      - ./app/my-app:/app
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:alpine
    depends_on:
      - next-app
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticbuild:/app/out
volumes:
  staticbuild: