# Install Node base image with Alpine Ubuntu
FROM node:20.11-alpine

RUN apk add --no-cache libc6-compat

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY pnpm-lock.yaml package.json ./

# Copy the rest of the files to the working directory
COPY . .

# Install dependencies
RUN corepack enable pnpm
RUN pnpm i --frozen-lockfile

# Generate Prisma Client
RUN npx prisma db push
RUN npx prisma generate

# Expose port 3000 from the container
EXPOSE 3001

# Start the Next.js server
CMD ["pnpm", "dev"]