import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Navbar from "@/components/Navbar"
import Providers from "@/components/Providers"
import { cn } from "@/lib/utils"
import "./globals.css"

import "react-loading-skeleton/dist/skeleton.css"
import { Toaster } from "@/components/ui/toaster"
import "simplebar-react/dist/simplebar.min.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Project Poco: Your Own Research Assistant",
  description: "generated by Amit",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const bgStyle = "min-h-screen font-sans antialiased"
  return (
    <html lang="en" className="light">
      <Providers>
        <body className={cn(bgStyle, inter.className)}>
          <Toaster />
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  )
}
