import { SessionProvider } from "next-auth/react"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { auth } from "@/auth"
import { cn } from "@/lib/utils"
import "@/app/globals.css"
import "react-loading-skeleton/dist/skeleton.css"
import { Toaster } from "@/components/ui/toaster"
import "simplebar-react/dist/simplebar.min.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Project Poco: Your Own Research Assistant",
  description: "generated by Amit",
}

const layout = async ({ children }: { children: React.ReactNode }) => {
  const session = await auth()

  const bgStyle = "min-h-screen font-sans antialiased"

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn(bgStyle, inter.className)}>
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  )
}

export default layout
